# Generated by Django 5.2.14 on 2026-08-04 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('book_no', models.CharField(max_length=50)),
                ('publisher', models.CharField(blank=True, default='', max_length=150)),
                ('author', models.CharField(blank=True, default='', max_length=150)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('rack_no', models.CharField(blank=True, default='', max_length=50)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('available', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['book_no', 'name'],
            },
        ),
    ]
