# Generated by Django 5.2.14 on 2026-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymember',
            name='member_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
