# Generated by Django 5.2.14 on 2026-08-04 09:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_librarymember_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('books_issued_count', models.PositiveIntegerField(default=1)),
                ('books_returned_count', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, default='Book Issued', max_length=255)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Issued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='management.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_issues', to='management.librarymember')),
            ],
            options={
                'verbose_name': 'Book Issue',
                'verbose_name_plural': 'Book Issues',
                'ordering': ['-issue_date', 'issue_id'],
            },
        ),
    ]
