# Generated by Django 5.2.14 on 2026-08-04 10:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_bookissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(default=datetime.date.today)),
                ('books_issued_count', models.PositiveIntegerField(default=1)),
                ('books_returned_count', models.PositiveIntegerField(default=1)),
                ('remarks', models.CharField(blank=True, default='Book Returned', max_length=255)),
                ('status', models.CharField(choices=[('Returned', 'Returned'), ('Partial Return', 'Partial Return'), ('Overdue Return', 'Overdue Return')], default='Returned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='management.book')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='management.bookissue')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_returns', to='management.librarymember')),
            ],
            options={
                'verbose_name': 'Book Return',
                'verbose_name_plural': 'Book Returns',
                'ordering': ['-return_date', 'return_id'],
            },
        ),
    ]
