# Generated by Django 5.2.14 on 2026-08-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_bookreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('coach', models.CharField(blank=True, default='', max_length=150)),
                ('coach_avatar', models.ImageField(blank=True, null=True, upload_to='sports_coaches/')),
                ('started_year', models.CharField(blank=True, default='2024', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
                'ordering': ['sport_id', 'name'],
            },
        ),
    ]
