# Generated by Django 5.2.14 on 2026-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('hostel_type', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Combined', 'Combined')], default='Boys', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('intake', models.PositiveIntegerField(default=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'ordering': ['hostel_id', 'name'],
            },
        ),
    ]
