# Generated by Django 5.2.14 on 2026-08-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50, unique=True)),
                ('room_no', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('One Bed', 'One Bed'), ('One Bed AC', 'One Bed AC'), ('Two Bed', 'Two Bed'), ('Two Bed AC', 'Two Bed AC'), ('Three Bed', 'Three Bed'), ('Four Bed', 'Four Bed')], default='One Bed', max_length=50)),
                ('no_of_beds', models.PositiveIntegerField(default=1)),
                ('cost_per_bed', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='management.hostel')),
            ],
            options={
                'verbose_name': 'Hostel Room',
                'verbose_name_plural': 'Hostel Rooms',
                'ordering': ['room_id', 'room_no'],
            },
        ),
    ]
