# Generated by Django 5.2.14 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_hostelroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hostel Room Type',
                'verbose_name_plural': 'Hostel Room Types',
                'ordering': ['type_id', 'name'],
            },
        ),
    ]
