# Generated by Django 5.2.14 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_hostelroomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=50, unique=True)),
                ('route_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transport Route',
                'verbose_name_plural': 'Transport Routes',
                'ordering': ['route_id', 'route_name'],
            },
        ),
    ]
