# Generated by Django 5.2.14 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_transportroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportPickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point_id', models.CharField(max_length=50, unique=True)),
                ('pickup_point', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transport Pickup Point',
                'verbose_name_plural': 'Transport Pickup Points',
                'ordering': ['pickup_point_id', 'pickup_point'],
            },
        ),
    ]
