# Generated by Django 5.2.14 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_transportpickuppoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportVehicleDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('driver_license_no', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transport Vehicle Driver',
                'verbose_name_plural': 'Transport Vehicle Drivers',
                'ordering': ['-created_at', 'driver_id'],
            },
        ),
    ]
