# Generated by Django 5.2.14 on 2026-08-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_transportvehicledriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=150)),
                ('made_of_year', models.CharField(blank=True, default='', max_length=10)),
                ('registration_no', models.CharField(blank=True, default='', max_length=50)),
                ('chassis_no', models.CharField(blank=True, default='', max_length=50)),
                ('seat_capacity', models.PositiveIntegerField(default=1)),
                ('gps_device_id', models.CharField(blank=True, default='', max_length=50)),
                ('driver_license_no', models.CharField(blank=True, default='', max_length=50)),
                ('driver_contact_no', models.CharField(blank=True, default='', max_length=30)),
                ('driver_address', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='management.transportvehicledriver')),
            ],
            options={
                'verbose_name': 'Transport Vehicle',
                'verbose_name_plural': 'Transport Vehicles',
                'ordering': ['-created_at', 'vehicle_id'],
            },
        ),
    ]
