# Generated by Django 5.2.14 on 2026-08-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_transportvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportAssignVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_vehicles', to='management.transportpickuppoint')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_vehicles', to='management.transportroute')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='management.transportvehicle')),
            ],
            options={
                'verbose_name': 'Transport Assign Vehicle',
                'verbose_name_plural': 'Transport Assign Vehicles',
                'ordering': ['-created_at', 'assign_id'],
            },
        ),
    ]
