# Generated by Django 5.2.14 on 2026-08-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_expensecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
