# Generated by Django 5.2.14 on 2026-07-29 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_alter_academicyear_id_alter_school_id"),
        ("people", "0003_leave_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeesGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeesType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Fees",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fees_code", models.CharField(blank=True, max_length=100)),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(choices=[("paid", "Paid"), ("unpaid", "Unpaid"), ("partial", "Partial")], default="unpaid", max_length=10)),
                ("ref_id", models.CharField(blank=True, max_length=50)),
                ("payment_mode", models.CharField(blank=True, choices=[("cash", "Cash"), ("cheque", "Cheque"), ("online", "Online Transfer"), ("card", "Card"), ("paytm", "Paytm"), ("cod", "Cash On Delivery")], max_length=20)),
                ("date_paid", models.DateField(blank=True, null=True)),
                ("discount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("fine", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_year", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="student_fees", to="core.academicyear")),
                ("collected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="collected_fees", to=settings.AUTH_USER_MODEL)),
                ("fees_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fees", to="fees.feesgroup")),
                ("fees_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fees", to="fees.feestype")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fees", to="people.student")),
            ],
            options={
                "verbose_name_plural": "Fees",
                "ordering": ["-created_at"],
            },
        ),
    ]
