# Generated by Django 5.2.14 on 2026-08-04 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_examattendance_student_and_more'),
        ('accounts', '0002_user_is_email_verified_otpverification'),
        ('communication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_for', models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('staffs', 'Staffs')], default='all', max_length=20)),
                ('category', models.CharField(choices=[('celebration', 'Celebration'), ('training', 'Training'), ('meeting', 'Meeting'), ('holidays', 'Holidays'), ('camp', 'Camp')], default='meeting', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='events/')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('classes', models.ManyToManyField(blank=True, related_name='events', to='academics.schoolclass')),
                ('roles', models.ManyToManyField(blank=True, related_name='events', to='accounts.role')),
                ('sections', models.ManyToManyField(blank=True, related_name='events', to='academics.section')),
                ('teachers', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
