# Generated by Django 5.2.14 on 2026-07-28 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_subject_options_subject_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='syllabus',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='academics.section'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='subject_group',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='academics.subject'),
        ),
    ]
