# Generated by Django 5.2.14 on 2026-07-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_grade_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
