# Generated by Django 5.2.14 on 2026-07-29 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_student_academic_year_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendances', to='people.student'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='people.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
