# Generated by Django 5.2.14 on 2026-08-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_examattendance_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Staff', 'Staff')], default='Teacher', max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Reason',
                'verbose_name_plural': 'Academic Reasons',
                'ordering': ['-created_at'],
            },
        ),
    ]
