# Generated by Django 5.2.14 on 2026-08-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_academicreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='room_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='section_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='routine_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
